# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 304fe322f6b6b6d4a9af4434952a8309ad287fccac547e27b89f898032d53bf26c7f721857a86fdb66ac0920ceb7064608237e9dd726539f7acfcb840c423044

test:
  secret_key_base: 345fcb7f15a4220a92fed82681b60c2d68fc073da34f01702937f457109c24e887196af14c677a9bc95571af1a18ad76498851b1e0dd42dafc71c43d56acf8ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
